default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: 1212
  database: condo_plus_development
  port: 5432

production:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV['PGDATABASE'] %>
  port: <%= ENV['PGPORT'] %>
